/**
 * PharmaGuard — Auto-Generated Clinical Note
 * Produces EHR-ready structured text from risk assessment results.
 */

// ── Generate a single drug clinical note ────────────────────────
function drugNote(r) {
    const risk = r.risk_assessment;
    const pgx = r.pharmacogenomic_profile;
    const rec = r.clinical_recommendation;
    const variants = pgx.detected_variants || [];

    const variantLines = variants.length > 0
        ? variants.map(v => `    - ${v.rsid} (${v.gene} ${v.star_allele || ""}): Genotype ${v.genotype}, Impact: ${v.functional_impact}`).join("\n")
        : "    - No pharmacogenomic variants detected; reference genotype assumed.";

    return `DRUG: ${r.drug}
  Gene: ${pgx.primary_gene}
  Diplotype: ${pgx.diplotype}
  Phenotype: ${pgx.phenotype}
  Risk Assessment: ${risk.risk_label} (Severity: ${risk.severity})
  Confidence: ${(risk.confidence_score * 100).toFixed(0)}%

  Recommendation: ${rec.action}
  Dosing Guideline: ${rec.dosing_guideline}
  Monitoring: ${rec.monitoring}${rec.alternatives?.length ? `\n  Alternatives: ${rec.alternatives.join(", ")}` : ""}

  CPIC Level: A (Strong)
  Reference: ${rec.cpic_guideline_reference}

  Detected Variants:
${variantLines}`;
}

// ── Generate full clinical note from all results ────────────────
export function generateClinicalNote(results, safetyIndex) {
    const ts = new Date().toISOString();
    const patientId = results[0]?.patient_id || "UNKNOWN";

    const drugSections = results.map(drugNote).join("\n\n" + "─".repeat(60) + "\n\n");

    const note = `══════════════════════════════════════════════════════════════
  PHARMACOGENOMIC CLINICAL NOTE
  PharmaGuard — Precision Medicine Report
══════════════════════════════════════════════════════════════

Patient ID: ${patientId}
Generated: ${new Date(ts).toLocaleString()}
Analysis Version: PharmaGuard v1.0

GENOMIC DRUG SAFETY INDEX: ${safetyIndex?.score ?? "N/A"} / 100 (${safetyIndex?.level ?? "Unknown"})

══════════════════════════════════════════════════════════════
PHARMACOGENOMIC ANALYSIS
══════════════════════════════════════════════════════════════

${drugSections}

══════════════════════════════════════════════════════════════
DISCLAIMER
══════════════════════════════════════════════════════════════

This report is generated by PharmaGuard for CLINICAL DECISION
SUPPORT only. It does not replace professional medical judgment.
All recommendations are based on CPIC guidelines and should be
reviewed by a qualified healthcare professional before clinical
action. Genetic test results should be confirmed by a CLIA-
certified laboratory.

Analysis Confidence: Based on available pharmacogenomic data.
CPIC Guideline Version: 2024
Generated: ${ts}
══════════════════════════════════════════════════════════════`;

    return note;
}

// ── Generate patient-friendly summary ───────────────────────────
export function generatePatientSummary(results, safetyIndex) {
    const lines = [`YOUR MEDICATION SAFETY REPORT`, `Generated: ${new Date().toLocaleDateString()}`, ""];

    if (safetyIndex) {
        const emoji = safetyIndex.score >= 80 ? "✅" : safetyIndex.score >= 50 ? "⚠️" : "🚫";
        lines.push(`${emoji} Overall Safety Score: ${safetyIndex.score} out of 100 (${safetyIndex.level})`);
        lines.push("");
    }

    for (const r of results) {
        const label = r.risk_assessment.risk_label;
        const emoji = label === "Safe" ? "✅" : label === "Adjust Dosage" ? "⚠️" : "🚫";
        lines.push(`${emoji} ${r.drug}`);

        if (label === "Safe") {
            lines.push(`   Your body processes this medicine normally. It is safe at standard doses.`);
        } else if (label === "Adjust Dosage") {
            lines.push(`   Your body handles this medicine a bit differently. Your doctor may adjust the dose.`);
        } else if (label === "Toxic") {
            lines.push(`   Your body could have a serious reaction to this medicine. Your doctor will likely use an alternative.`);
        } else if (label === "Ineffective") {
            lines.push(`   This medicine may not work well for you. Your doctor can suggest better options.`);
        }
        lines.push("");
    }

    lines.push("─".repeat(50));
    lines.push("This report is for informational purposes only.");
    lines.push("Please discuss your results with your doctor.");

    return lines.join("\n");
}
